const CONFIG = {
    titleWeb: "Quà tặng 20/10 nè mọi người",
    introTitle: 'Quà tặng 20/10 nè mọi người',
    introDesc: `Mọi người sẵn sàng nhận quà chưa`,
    btnIntro: '^^Đã sẵn sàng^^',
    title: 'Trước khi nhận quà có câu hỏi nhỏ là "Ban tuyển sinh Greenwich Cần Thơ "Tí nị" dễ thương, đáng yêu nhất đúng không ạ? 🥰',
    desc: 'Mọi người không cần dối lòng đâu',
    btnYes: 'Chắc chắn rồi',
    btnNo: 'Không nha :3',
    question: 'Món quà mọi người muốn nhận nhất bây giờ là gì nhỉ?',
    btnReply: 'Gửi yêu cầu món quà',
    reply: 'À món quà đó vượt tầm kiểm soát của em nhe, nên em tặng mọi đôi câu chúc ngắn gọn thôi',
    mess: 'Nhận dịp quốc tế Phụ nữ 20/10, em có đôi lời chúc ngắn gọn xin gửi đến những "Bông hoa" của Ban tuyển sinh là sẽ tay ôm nhiều hoa, giỏ đựng nhiều quà, được đi chơi xa, ăn uống thả ga, tiền không phải trả. Chúc chị em gặp nhiều may mắn và hạnh phúc mỗi ngày.',
    messDesc: 'Không cần cảm động đâu mai mốt em order đồ ăn ủng hộ em là được rồi.',
    btnAccept: 'Okiiiii lun',
